#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM tabCombo[] = {KC_A, KC_SCLN, COMBO_END};
const uint16_t PROGMEM entCombo[] = {KC_H, KC_J, COMBO_END};
const uint16_t PROGMEM escCombo[] = {LGUI_T(KC_Q), KC_P, COMBO_END};
const uint16_t PROGMEM escLeftCombo[] = {KC_W, KC_E, COMBO_END};
const uint16_t PROGMEM entComboAlt[] = {KC_K, KC_L, COMBO_END};
const uint16_t PROGMEM tabComboAlt[] = {KC_D, KC_S, COMBO_END};
const uint16_t PROGMEM bkspCombo[] = {KC_S, KC_F, COMBO_END};
const uint16_t PROGMEM bkspNumCombo[] = {KC_RBRC, KC_RCBR, COMBO_END};
const uint16_t PROGMEM delCombo[] = {KC_J, KC_L, COMBO_END};
const uint16_t PROGMEM tildeCombo[] = {KC_A, KC_D, COMBO_END};

const uint16_t PROGMEM eqCombo[] = {KC_F, KC_J, COMBO_END};
const uint16_t PROGMEM hyphenCombo[] = {KC_D, KC_K, COMBO_END};
const uint16_t PROGMEM underCombo[] = {KC_S, KC_L, COMBO_END};

const uint16_t PROGMEM nexttab[] = {KC_Q, KC_R, COMBO_END};
const uint16_t PROGMEM prevtab[] = {KC_Q, KC_W, COMBO_END};
const uint16_t PROGMEM closetab[] = {KC_W, KC_E, KC_R, COMBO_END};
const uint16_t PROGMEM refreshtab[] = {KC_W, KC_R, COMBO_END};
const uint16_t PROGMEM copy[] = {LSFT_T(KC_Z), KC_C, COMBO_END};
const uint16_t PROGMEM paste[] = {LSFT_T(KC_Z), KC_V, COMBO_END};
const uint16_t PROGMEM ctrl[] = {LSFT_T(KC_Z), KC_B, COMBO_END};

combo_t key_combos[COMBO_COUNT] = {

    COMBO(eqCombo, KC_EQL),
    COMBO(hyphenCombo, KC_MINS),
    COMBO(underCombo, KC_UNDS),
    COMBO(tildeCombo, KC_TILD),

    COMBO(escCombo, KC_ESC),
    COMBO(entCombo, KC_ENT),
    COMBO(delCombo, KC_DEL),
    COMBO(tabCombo, KC_TAB),
    COMBO(bkspCombo, KC_BSPC),
    COMBO(bkspNumCombo, KC_BSPC),
    COMBO(entComboAlt, KC_ENT),
    COMBO(tabComboAlt, KC_TAB),
    COMBO(nexttab, LCTL(KC_TAB)),
    COMBO(prevtab, S(C(KC_TAB))),
    COMBO(closetab, LCTL(KC_W)),
    COMBO(refreshtab, LCTL(KC_R)),
    COMBO(escLeftCombo, KC_ESC),
    COMBO(copy, LCTL(KC_C)),
    COMBO(paste, LCTL(KC_V)),
    COMBO(ctrl, KC_LCTL),
};
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x6_3(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, LSFT_T(KC_Z), LGUI_T(KC_X), KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, LGUI_T(KC_DOT), LSFT_T(KC_SLSH), KC_RSFT, KC_LGUI, OSL(1), KC_LSFT, LCTL_T(KC_SPC), OSL(5), LALT_T(KC_QUOT)),
	[1] = LAYOUT_split_3x6_3(KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_NO, KC_NO, KC_LPRN, KC_LBRC, KC_RBRC, KC_RPRN, KC_PLUS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_QUOT, KC_NO, KC_NO, KC_TILD, KC_LCBR, KC_RCBR, KC_GRV, KC_EQL, KC_PIPE, KC_BSLS, KC_UNDS, KC_MINS, KC_DQUO, KC_NO, KC_LGUI, KC_TRNS, KC_LCTL, KC_NO, MO(3), KC_NO),
	[2] = LAYOUT_split_3x6_3(KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_LCBR, KC_RCBR, KC_GRV, KC_MINS, KC_UNDS, KC_PLUS, KC_EQL, KC_QUOT, KC_NO, KC_NO, KC_BSLS, KC_PIPE, KC_PLUS, KC_EQL, KC_TILD, KC_COLN, KC_SCLN, KC_LT, KC_GT, KC_DQUO, KC_NO, KC_END, KC_NO, KC_NO, OSL(4), LT(3,KC_NO), KC_LCTL),
	[3] = LAYOUT_split_3x6_3(KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_HOME, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLU, KC_VOLU, KC_PGUP, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_NO, KC_MPRV, KC_MPLY, KC_MNXT, KC_VOLD, KC_VOLD, KC_PGDN, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[4] = LAYOUT_split_3x6_3(KC_NO, KC_LBRC, KC_7, KC_8, KC_9, KC_RBRC, KC_NO, KC_LPRN, KC_NO, KC_RPRN, KC_BSLS, KC_NO, KC_NO, KC_SCLN, KC_4, KC_5, KC_6, KC_EQL, KC_NO, KC_LCBR, KC_RSFT, KC_RCBR, KC_QUOT, KC_NO, KC_NO, KC_GRV, KC_1, KC_2, KC_3, KC_MINS, KC_NO, KC_LBRC, KC_NO, KC_RBRC, KC_SLSH, KC_NO, KC_NO, KC_NO, KC_0, KC_SPC, KC_NO, KC_NO),
	[5] = LAYOUT_split_3x6_3(KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_LPRN, KC_CIRC, KC_AMPR, KC_ASTR, KC_RPRN, KC_EQL, KC_4, KC_5, KC_6, KC_PLUS, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_LCBR, KC_RCBR, KC_GRV, KC_ASTR, KC_1, KC_2, KC_3, KC_BSLS, KC_NO, KC_NO, MO(3), KC_NO, KC_COLN, KC_TRNS, KC_DOT)
};

